In [2]:
import numpy as np

#### Задание 1

In [40]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [10]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

#### Задание 2

In [11]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

In [42]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
print(a_centered_sp)
print(f'{a_centered_sp / (a.shape[0] - 1):.1f}')

8.0
2.0


#### Задание 4**

In [44]:
np.cov(a.T)[0, 1]

2.0