#### **Задание на повторение

In [42]:
import numpy as np

#### No1

In [43]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### No2

In [44]:
for i in [2, 3, 4, 6, 12]:
    print(f'{np.reshape(a, (i, int(12/i)))}\n')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]



#### No3

In [45]:
a1 = np.reshape(a, (-1, 6))
a2 = np.reshape(a, (-1, 2))
a3 = np.reshape(a, (3, -1))
a4 = np.reshape(a, (4, -1))
a5 = np.reshape(a, (12, -1))
print(f'{a1}\n\n{a2}\n\n{a3}\n\n{a4}\n\n{a5}')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### No4

Нет, т.к. одномерный массив - это список, а массив из одного столбца - это список списков, просто в каждом списке располагается всего один элемент. Доступ к элементу одномерного массива будет по одному индексу, и в результате выводится число (в нашем случае с массивом a). А доступ к элементу двумерного массива - будет по двум индексам.

In [46]:
print(f'a[0]: {a[0]} - {type(a[0])}')
print(f'a5[0]: {a5[0]} - {type(a5[0])}')
print(f'a5[0][0]: {a5[0][0]} - {type(a5[0][0])}')

a[0]: 12 - <class 'numpy.int64'>
a5[0]: [12] - <class 'numpy.ndarray'>
a5[0][0]: 12 - <class 'numpy.int64'>


#### No5

In [47]:
aa = np.random.randn(3, 4)
aaa = aa.reshape(1, aa.size)
print(f'aa:\n{aa}\n\naaa: {aaa}')

aa:
[[-1.48421968 -1.34727624  1.50072885  0.31827306]
 [ 1.03937254  0.45043015 -0.67448915  0.45998984]
 [-0.50428437 -0.70143794  0.6632496  -0.48716513]]

aaa: [[-1.48421968 -1.34727624  1.50072885  0.31827306  1.03937254  0.45043015
  -0.67448915  0.45998984 -0.50428437 -0.70143794  0.6632496  -0.48716513]]


#### No6

In [48]:
a_6 = np.arange(20, 0, -2)
a_6

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### No7

In [49]:
b = np.arange(20, 1, -2)
bb = b[:, np.newaxis]
bb

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

a_6 - одномерный массив, строка; bb - двумерный массив, столбец

#### No8

In [50]:
a8 = np.zeros((2, 2))
b8 = np.ones((3, 2))
c8 = np.vstack((a8, b8))
c8

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### No9

In [51]:
a9 = np.arange(12)
A9 = a9.reshape(4, 3)
At = A9.T
B9 = np.dot(A9, At)

print(B9)
print(np.shape(B9))
print(np.linalg.det(B9))

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
(4, 4)
0.0


Нельзя посчитать обратную матрицу для B9, т.к. её определитель равен 0.

#### No10

In [52]:
np.random.seed(42)
a10 = np.random.rand(1)
print(a10)

[0.37454012]


#### No11

In [53]:
c11 = np.random.randint(0, 16, 16)
c11

array([12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7])

#### No12

In [54]:
C12 = np.reshape(c11, (4, 4))
D12 = B9 + C12  * 10
D_inv = np.linalg.inv(D12)
print(f'D12:\n{D12}\n')
print(f'Определитель D12:\n{np.linalg.det(D12):.1f}\n')
print(f'Ранг D12:\n{np.linalg.matrix_rank(D12)}\n')
print(f'Обратная матрица D_inv:\n{D_inv}')

D12:
[[125 154 123 102]
 [134  90 146 212]
 [ 43 146 249 312]
 [102 162 242 372]]

Определитель D12:
-149097600.0

Ранг D12:
4

Обратная матрица D_inv:
[[ 0.0004711   0.0111539  -0.00253901 -0.00435621]
 [ 0.00957225 -0.01715762 -0.00876527  0.01450486]
 [-0.00167085  0.01408514  0.02130578 -0.02543824]
 [-0.00321078 -0.00474937 -0.0093469   0.01411451]]


#### No13

In [55]:
D_inv2 = np.zeros((4, 4))
for i in range(len(D_inv2[0])):
    for j in range(len(D_inv2[0])):
        if D_inv[i][j] > 0:
            D_inv2[i][j] = 1
        else:
            continue
print(D_inv2)

[[1. 1. 0. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
E = np.where(D_inv2 == 1, B9, C12)
print(E)

[[  5  14  10   7]
 [ 14   4   6 122]
 [  2  86 149  10]
 [  7   4   3 302]]
